---
title: "Site distribution analysis"
author: "Enrico Lucci"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Site distribution analysis

### Sites per region
```{r sites per region, echo=FALSE, message=FALSE, warning=FALSE}
library(raster)

sites<-shapefile("data/CA_BA_sites.shp")
studyarea<-shapefile("data/studyareaWGS84.shp")
plot(studyarea)
plot(sites, add = TRUE, col = "red")

```


```{r density, echo=FALSE, warning=FALSE, message=FALSE}
df<-as.data.frame(sites)

library(dplyr)
df2 = df%>%
  group_by(regione) %>%
  summarise(counts = n())
df2

df3 <- df2 %>%
  arrange(desc(regione)) %>%
  mutate(prop = round(counts*100/sum(counts), 1))
df3

library(ggplot2)
library(ggthemes)


p<-ggplot(df2, aes(regione, counts, fill=regione)) + geom_col() + xlab("") + 
  ylab("number of sites") + theme_minimal()+  theme(legend.position="none")+theme(text=element_text(size = 16))
p

pperc<-ggplot(df3, aes(regione, prop)) + geom_col() + xlab("") + ylab("% of sites")
pperc
```


### Sites per elevation class

```{r sites per elev, echo=FALSE, message=FALSE, warning=FALSE}
library(terra)
elev_class<-rast("data/raster/rec_elev.tiff")
sites<-vect("data/CA_BA_sites.shp")


sites_elev<-extract(elev_class, sites, bind = TRUE)
df<-as.data.frame(sites_elev)
View(df)

library(dplyr)
df2 = df%>%
  group_by(regione,Abr_Mol_Pug) %>%
  summarise(counts = n())
df2


id = (c("1","2","3","4","5"))
cat = c("0-100","100-200","200-500","500-1000","1000-1500")
classes = data.frame(cat, id)
print(classes)


df2 <- merge(x=df2,y=classes, 
             by.x=c("Abr_Mol_Pug"), by.y=c("id"))
df2


library(ggplot2)
library(ggthemes)
library(forcats)



SE_plot <-ggplot(df2,aes(x=reorder(cat, Abr_Mol_Pug), y=counts, fill = regione)) + geom_col(stat="identity")+
  labs(x="elev classes (m asl)", y="number of sites") +theme(legend.position="right", legend.box = "horizontal", 
                           axis.text = element_text(size = 9), legend.text = element_text(size = 9), 
                           legend.title = element_blank(), axis.title.y = element_text(size = 9), axis.text.x = element_text(size = 9, angle=0))


SE_plot


plot(elev_class, main = "elevation classes (m asl)", col=topo.colors(6), legend = FALSE)
  legend(13,40.9, title="classes",
   c("0-100","100-200","200-500","500-1000","1000-1500",">1500"), 
   fill=topo.colors(6), cex=0.8)
  plot(sites, add=T, col = "red", cex = 0.5)

```


### Topographic characterisation of sites per phase

```{r TPI elev, message=FALSE, warning=FALSE, echo=FALSE}
library(terra)

sites_CA<-vect("data/CA_sites.shp")
sites_BA<-vect("data/BA_sites.shp")

dem<-rast("~/GIS_ModLandWGS84/raster/Abr_Mol_Pug.tif")
elev_class<-rast("data/raster/rec_elev.tiff")

#tpiw <- function(x, w = n) {
 # m <- matrix(1/(w^2-1), nc=w, nr=w)
  #m[ceiling(0.5 * length(m))] <- 0
  #f <- focal(x, m)
  #x - f
  #}

#TPI15<-tpiw(dem, w = 15)



#writeRaster(TPI15, '~/R analisi/ModLand/data/raster/TPI15.tiff', overwrite=TRUE)

TPI15<-rast("data/raster/TPI15.tiff")


library(raster)
dem<-raster(dem)
TPI15<-raster(TPI15)
stack_raster<-rast(stack(TPI15, dem))
plot(stack_raster)


#Copper Age sites
dfCA<-extract(stack_raster, sites_CA, bind = TRUE)

dfCA<-as.data.frame(dfCA)

colnames(dfCA)[36]  <- "TPI"
colnames(dfCA)[37]  <- "elev" 
dfCA$TPI[is.na(dfCA$TPI)] <- 0
View(dfCA)

#Bronze Age sites
dfBA<-extract(stack_raster, sites_BA, bind = TRUE)

dfBA<-as.data.frame(dfBA)

colnames(dfBA)[36]  <- "TPI"
colnames(dfBA)[37]  <- "elev" 
dfBA$TPI[is.na(dfBA$TPI)] <- 0
View(dfBA)



library(ggplot2)
library(ggthemes)
pCA<-ggplot(dfCA, aes(x = TPI, y = elev, col = regione)) + geom_point() + 
  geom_density_2d() + facet_wrap(~ regione) + labs(title = "Copper Age sites")
pCA

pBA<-ggplot(dfBA, aes(x = TPI, y = elev, col = regione)) + geom_point() + 
  geom_density_2d() + facet_wrap(~ regione)+ labs(title = "Bronze Age sites")
pBA


```








